# Generated by Django 4.0.5 on 2022-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frst_name', models.CharField(max_length=80)),
                ('lst_name', models.CharField(max_length=40)),
                ('addr', models.CharField(max_length=200)),
                ('webst', models.CharField(max_length=40)),
                ('fb', models.CharField(max_length=40)),
                ('remarks', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
