# Generated by Django 4.0.5 on 2022-06-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paws_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('with_legal_case', models.BooleanField()),
                ('rescuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paws_db.client')),
            ],
            options={
                'db_table': 'rescue_detail',
            },
        ),
        migrations.CreateModel(
            name='FosterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_date', models.DateField()),
                ('ret_date', models.DateField()),
                ('fosterer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paws_db.client')),
            ],
            options={
                'db_table': 'foster_detail',
            },
        ),
    ]
