# Generated by Django 4.0.5 on 2022-07-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_db', '0003_userauth_clientcontact_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='role',
            field=models.CharField(choices=[('gst', 'Guest'), ('adm', 'Admin'), ('vet', 'Veterinarian')], default='gst', max_length=3),
        ),
    ]
